return {
    general = {
        name = "my-setup",
        max_fps = 60,
        gaps = 4,
        border_width = 2,
        focus_follows_mouse = false,
        smart_gaps = true,
    },
    animations = {
        enabled = true,
        duration = 300,
        easing = "ease_out_cubic",
        open_animation = "fade_in",
        close_animation = "fade_out",
        workspace_animation = "slide_horizontal",
    },
    effects = {
        blur_enabled = false,
        blur_radius = 10,
        shadows_enabled = true,
        shadow_offset_x = 0,
        shadow_offset_y = 4,
        shadow_blur = 12,
        shadow_color = "#000000",
        rounded_corners = true,
        corner_radius = 8,
    },
    bar = {
        enabled = true,
        position = "top",
        height = 30,
        modules_left = { "workspaces", "separator" },
        modules_center = { "clock" },
        modules_right = { "network", "battery", "tray" },
    },
    keybinds = {
        mod = "Super",
        launcher = "Super+Space",
        terminal = "Super+Return",
        close = "Super+Q",
        fullscreen = "Super+F",
        floating = "Super+Shift+Space",
        layout_next = "Super+Space",
        workspace_next = "Super+bracketright",
        workspace_prev = "Super+bracketleft",
        workspace_1 = "Super+1",
        workspace_2 = "Super+2",
        workspace_3 = "Super+3",
        workspace_4 = "Super+4",
        workspace_5 = "Super+5",
        workspace_6 = "Super+6",
        workspace_7 = "Super+7",
        workspace_8 = "Super+8",
        workspace_9 = "Super+9",
        workspace_10 = "Super+0",
    },
    xwayland = {
        enabled = true,
    },
    plugins = {
        {
            path = "/usr/lib/waydri/plugins/statusbar.so",
            enabled = true,
        },
    },
}
