default-sample-format = s16le
default-sample-rate = 44100
default-sample-channels = 2
default-channel-map = front-left,front-right

default-fragments = 2
default-fragment-size-msec = 25

resample-method = speex-float-4
enable-lfe-remixing = no

high-priority = yes
nice-level = -11
realtime-scheduling = yes
realtime-priority = 5

daemonize = no

exit-idle-time = -1
autospawn = yes
