return {
    ["Super+ctrl+Left"] = "media_prev_track",
    ["Super+ctrl+Right"] = "media_next_track",
    ["Super+ctrl+Space"] = "media_play_pause",
    ["Super+ctrl+Up"] = "volume_up",
    ["Super+ctrl+Down"] = "volume_down",
    ["Super+ctrl+m"] = "mute_toggle",
    ["Super+Return"] = "terminal",
    ["Super+q"] = "close_window",
    ["Super+f"] = "toggle_fullscreen",
    ["Super+space"] = "toggle_floating",
    ["Super+1"] = "workspace:1",
    ["Super+2"] = "workspace:2",
    ["Super+3"] = "workspace:3",
    ["Super+4"] = "workspace:4",
    ["Super+5"] = "workspace:5",
    ["Super+Tab"] = "next_workspace",
    ["Super+Shift+Tab"] = "prev_workspace",
    ["Super+Shift+q"] = "quit",
    ["Super+ctrl+r"] = "reload_config",
}
