[env]
CC = "aarch64-linux-android-clang"
AR = "aarch64-linux-android-ar"

[target.aarch64-linux-android]
linker = "aarch64-linux-android-clang"
rustflags = ["-Lnative=/root/Waydri/core/native-libs"]

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi24-clang"
rustflags = ["-Lnative=/root/Waydri/core/native-libs"]

[target.i686-linux-android]
linker = "i686-linux-android24-clang"
rustflags = ["-Lnative=/root/Waydri/core/native-libs"]

[target.x86_64-linux-android]
linker = "x86_64-linux-android24-clang"
rustflags = ["-Lnative=/root/Waydri/core/native-libs"]