return {
    terminal = "alacritty",
    file_manager = "thunar",
    browser = "firefox",
    launcher = "wofi",
    launcher_args = {"--show", "drun"},
    screenshot = "grim -g \"$(slurp)\" - | wl-copy",
    lock_screen = "swaylock -c 1e1e2e",
    volume_up = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+",
    volume_down = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-",
    volume_mute = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle",
    brightness_up = "brightnessctl set +5%",
    brightness_down = "brightnessctl set 5%-",
    bar = "waydri-bar",
    notifications = "waydri-notifications",
    wallpaper = "swww init && swww img /usr/share/waydri/wallpaper.png",
    idle_timeout = 300,
    lock_on_idle = true,
    lock_on_suspend = true,
}
